// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SillyPuttConstants
{
        public const string achievement_flying_high = "CggIybOGnkQQAhAE"; // <GPGSID>
        public const string achievement_moving_on_up = "CggIybOGnkQQAhAA"; // <GPGSID>
        public const string leaderboard_best_scores_level_3 = "CggIybOGnkQQAhAJ"; // <GPGSID>
        public const string leaderboard_best_scores_level_2 = "CggIybOGnkQQAhAI"; // <GPGSID>
        public const string leaderboard_best_scores_level_1 = "CggIybOGnkQQAhAH"; // <GPGSID>
        public const string achievement_the_end_of_the_road = "CggIybOGnkQQAhAC"; // <GPGSID>
        public const string achievement_high_achiever = "CggIybOGnkQQAhAD"; // <GPGSID>
        public const string achievement_steady_as_she_goes = "CggIybOGnkQQAhAB"; // <GPGSID>

}

